query test {
    git(url: "https://github.com/portward/portward") {
        branch(name: "main") {
            tree {
                bats(args: ["-r"]) {
                    id
                }
            }
        }
    }
}
