Set Shell fish

Set FontSize 10
Set FontSize 20
Set FontSize 40

Set FontFamily "Monoflow"

Set Width 300

Set Height 1000

Set LetterSpacing 20

Set LineHeight 1.8

Set TypingSpeed 500ms # 500ms
Set TypingSpeed 1s # 1s
Set TypingSpeed 0.1

Set Theme "Catppuccin Frappe"

Set Padding 0

Set Margin 60
Set MarginFill "#6B50FF"

Set WindowBar Colorful

# You'll likely want to add a Margin + MarginFill if you use BorderRadius.
Set Margin 20
Set MarginFill "#674EFF"
Set BorderRadius 10

Set Framerate 60

Set PlaybackSpeed 0.5 # Make output 2 times slower
Set PlaybackSpeed 1.0 # Keep output at normal speed (default)
Set PlaybackSpeed 2.0 # Make output 2 times faster

Set LoopOffset 5 # Start the GIF at the 5th frame
Set LoopOffset 50% # Start the GIF halfway through

Set CursorBlink false
